/**
 * Downtime Action Types and Creators
 *
 * Action constants and factory functions for downtime task operations.
 */

import type {
  DowntimeActivityType,
  ActivityData,
  DowntimeTask,
  TaskResults,
} from '../../types/downtime';

// ============================================================================
// ACTION TYPE CONSTANTS
// ============================================================================

export const DOWNTIME_TASK_CREATE = 'downtime/taskCreate' as const;
export const DOWNTIME_TASK_UPDATE = 'downtime/taskUpdate' as const;
export const DOWNTIME_TASK_BEGIN_RESOLVE = 'downtime/taskBeginResolve' as const;
export const DOWNTIME_TASK_RESOLVE = 'downtime/taskResolve' as const;
export const DOWNTIME_TASK_CANCEL = 'downtime/taskCancel' as const;
export const DOWNTIME_TASK_REORDER = 'downtime/taskReorder' as const;

// ============================================================================
// PAYLOAD TYPES
// ============================================================================

/**
 * Payload for creating a new downtime task.
 * ID and timestamps are generated by the reducer.
 */
export interface CreateTaskPayload {
  /** Type of activity being performed */
  activityType: DowntimeActivityType;
  /** Day number when this task is scheduled */
  dayKey: number;
  /** Time slot within the day (0-based index) */
  slot: number;
  /** Character ID of the primary worker leading this task */
  leaderId: string;
  /** Character IDs of helpers assisting with this task */
  helperIds: string[];
  /** Activity-specific configuration data */
  activityData: ActivityData;
}

/**
 * Payload for updating an existing task.
 * Only specified fields will be modified.
 */
export interface UpdateTaskPayload {
  /** ID of the task to update */
  taskId: string;
  /** Fields to update (partial task data) */
  changes: Partial<Omit<DowntimeTask, 'id' | 'createdAt'>>;
}

// ============================================================================
// ACTION TYPES
// ============================================================================

export type DowntimeAction =
  | { type: typeof DOWNTIME_TASK_CREATE; payload: CreateTaskPayload }
  | { type: typeof DOWNTIME_TASK_UPDATE; payload: UpdateTaskPayload }
  | { type: typeof DOWNTIME_TASK_BEGIN_RESOLVE; payload: { taskId: string } }
  | { type: typeof DOWNTIME_TASK_RESOLVE; payload: { taskId: string; results: TaskResults } }
  | { type: typeof DOWNTIME_TASK_CANCEL; payload: { taskId: string } }
  | { type: typeof DOWNTIME_TASK_REORDER; payload: { taskIds: string[] } };

// ============================================================================
// ACTION CREATORS
// ============================================================================

/**
 * Creates a new downtime task.
 * The reducer will generate the ID and set initial timestamps.
 */
export function createTask(payload: CreateTaskPayload): DowntimeAction {
  return { type: DOWNTIME_TASK_CREATE, payload };
}

/**
 * Updates specific fields on an existing task.
 * Only the fields specified in `changes` will be modified.
 */
export function updateTask(payload: UpdateTaskPayload): DowntimeAction {
  return { type: DOWNTIME_TASK_UPDATE, payload };
}

/**
 * Transitions a task to 'in_progress' status.
 * Call this when starting to resolve a task.
 */
export function beginResolveTask(taskId: string): DowntimeAction {
  return { type: DOWNTIME_TASK_BEGIN_RESOLVE, payload: { taskId } };
}

/**
 * Resolves a task with the given results.
 * Sets status to 'resolved' and attaches the results.
 * This operation is idempotent - resolving twice has no additional effect.
 */
export function resolveTask(taskId: string, results: TaskResults): DowntimeAction {
  return { type: DOWNTIME_TASK_RESOLVE, payload: { taskId, results } };
}

/**
 * Cancels a task.
 * Sets status to 'cancelled' but does NOT remove the task from state.
 * Cancelled tasks are kept as tombstones for audit purposes.
 */
export function cancelTask(taskId: string): DowntimeAction {
  return { type: DOWNTIME_TASK_CANCEL, payload: { taskId } };
}

/**
 * Reorders the task list for UI display.
 * Replaces the entire taskOrder array.
 */
export function reorderTasks(taskIds: string[]): DowntimeAction {
  return { type: DOWNTIME_TASK_REORDER, payload: { taskIds } };
}
